# Site settings
title: 闭眼狐小狸
header-img: "img/green.jpg"
tagline: "狐小狸"  
description: "狐小狸|闭眼狐小狸"  
baseurl: ""
url: "http://kkryoung.github.io"  

# About/contact
owner: 
  name: "狐小狸"
  email: 
  bio: ""

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/狐狸.jpg

douban_username:  
twitter_username: 
github_username: 
facebook_username: 
weibo_username: 
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 3
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Guangzhou

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "狐小狸"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : "kkryoung"
  disqus :
      short_name : 

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation

## 文章末尾是否显示打赏按钮
donate: 
  enable: true
  text: Enjoy it ? Donate me !  欣赏此文？求鼓励，求支持！
  alipay: "img/微信打赏.jpg"
  wechat: "img/支付宝打赏.jpg"
